#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative --exclude=.node_modules --exclude=bower_components -L - -f"$dir/$$.tags"
  mv "$dir/$$.tags" "$dir/tags"
